disabled_rules:
  - trailing_whitespace
  - vertical_whitespace
opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - sorted_imports
line_length:
  warning: 120
  error: 140
included:
  - ShiftPro
  - ShiftProTests
