import SwiftUI
import SwiftData

/// A simple, visual pattern builder where users tap on a grid to design their shift cycle
struct SimplePatternBuilderView: View {
    @Environment(\.modelContext) private var modelContext
    @Environment(\.dismiss) private var dismiss
    @Environment(\.accessibilityReduceMotion) private var reduceMotion
    @Query(sort: [SortDescriptor(\UserProfile.createdAt, order: .forward)])
    private var profiles: [UserProfile]

    @State private var patternName = ""
    @State private var cycleLength = 4
    @State private var workDays: Set<Int> = [0, 1]  // Days that are work days (0-indexed)
    @State private var startTime = Calendar.current.date(bySettingHour: 9, minute: 0, second: 0, of: Date()) ?? Date()
    @State private var endTime = Calendar.current.date(bySettingHour: 17, minute: 0, second: 0, of: Date()) ?? Date()
    @State private var currentDayInCycle = 0  // Which day of the pattern are we on today?
    @State private var isApplying = false
    @State private var showSuccess = false
    @State private var showError = false
    @State private var errorMessage = ""
    @State private var isNameCustomized = false
    @State private var isSettingAutoName = false
    @State private var isCustomLength = false
    @State private var selectedColorHex = ShiftProColors.patternColors[1]  // Default green
    @State private var selectedShiftCode = "E"  // Default Early

    private let engine = PatternEngine()

    var body: some View {
        NavigationStack {
            formScrollView
                .background(ShiftProColors.background.ignoresSafeArea())
                .navigationTitle("Build Pattern")
                .navigationBarTitleDisplayMode(.inline)
                .toolbar { cancelToolbarItem }
                .onAppear { updateAutoName() }
                .onChange(of: workDays) { _, _ in updateAutoName() }
                .onChange(of: cycleLength) { _, _ in
                    normalizeCycleLength()
                    updateAutoName()
                }
                .alert("Pattern Created!", isPresented: $showSuccess) {
                    Button("Done") { dismiss() }
                } message: {
                    Text("Your pattern '\(resolvedPatternName)' has been created and shifts have been scheduled for the next 2 months.")
                }
                .alert("Error", isPresented: $showError) {
                    Button("OK", role: .cancel) {}
                } message: {
                    Text(errorMessage)
                }
        }
    }

    // MARK: - Body Subsections

    private var formScrollView: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: ShiftProSpacing.large) {
                headerSection
                patternNameSection
                cycleLengthSection
                workDaysSection
                shiftTimesSection
                shiftLabelSection
                colorPickerSection
                previewSection
                createButtonSection
            }
            .padding(ShiftProSpacing.medium)
        }
    }

    private var cancelToolbarItem: some ToolbarContent {
        ToolbarItem(placement: .cancellationAction) {
            Button("Cancel") { dismiss() }
        }
    }

    private var headerSection: some View {
        Text("Build Your Pattern")
            .font(ShiftProTypography.title)
            .foregroundStyle(ShiftProColors.ink)
    }

    private var patternNameSection: some View {
        VStack(alignment: .leading, spacing: ShiftProSpacing.small) {
            Text("Pattern Name")
                .font(ShiftProTypography.headline)
                .foregroundStyle(ShiftProColors.ink)

            TextField("e.g., \(autoGeneratedName)", text: $patternName)
                .textFieldStyle(.roundedBorder)
                .foregroundStyle(ShiftProColors.ink)
                .onChange(of: patternName) { _, newValue in
                    guard !isSettingAutoName else { return }
                    let trimmed = newValue.trimmingCharacters(in: .whitespacesAndNewlines)
                    if trimmed.isEmpty {
                        isNameCustomized = false
                        updateAutoName()
                    } else {
                        isNameCustomized = true
                    }
                }
        }
    }

    private var cycleLengthSection: some View {
        VStack(alignment: .leading, spacing: ShiftProSpacing.small) {
            Text("Cycle Length")
                .font(ShiftProTypography.headline)
                .foregroundStyle(ShiftProColors.ink)

            cycleLengthButtons

            if isCustomLength {
                customLengthSlider
            }
        }
    }

    private var cycleLengthButtons: some View {
        ScrollView(.horizontal, showsIndicators: false) {
            HStack(spacing: ShiftProSpacing.small) {
                ForEach([4, 5, 7, 14, 21, 28], id: \.self) { length in
                    cycleLengthButton(for: length)
                }
                customLengthButton
            }
            .padding(.trailing, ShiftProSpacing.medium)
        }
    }

    private func cycleLengthButton(for length: Int) -> some View {
        Button {
            let anim: Animation? = reduceMotion ? nil : .spring(response: 0.35, dampingFraction: 0.7)
            withAnimation(anim) {
                cycleLength = length
                isCustomLength = false
                normalizeCycleLength()
            }
            HapticManager.fire(.selection, enabled: !reduceMotion)
        } label: {
            Text("\(length)")
                .font(ShiftProTypography.headline)
                .frame(width: 48, height: 48)
                .background(cycleLength == length && !isCustomLength ? ShiftProColors.accent : ShiftProColors.surface)
                .foregroundStyle(cycleLength == length && !isCustomLength ? .white : ShiftProColors.ink)
                .clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous))
        }
        .shiftProPressable(scale: 0.97, opacity: 0.94, haptic: nil)
    }

    private var customLengthButton: some View {
        Button {
            let anim: Animation? = reduceMotion ? nil : .spring(response: 0.35, dampingFraction: 0.7)
            withAnimation(anim) {
                isCustomLength = true
            }
            HapticManager.fire(.selection, enabled: !reduceMotion)
        } label: {
            Text("Custom")
                .font(ShiftProTypography.subheadline)
                .frame(width: 80, height: 48)
                .background(isCustomLength ? ShiftProColors.accent : ShiftProColors.surface)
                .foregroundStyle(isCustomLength ? .white : ShiftProColors.ink)
                .clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous))
        }
        .shiftProPressable(scale: 0.97, opacity: 0.94, haptic: nil)
    }

    private var customLengthSlider: some View {
        VStack(alignment: .leading, spacing: ShiftProSpacing.extraSmall) {
            Text(customLengthLabel)
                .font(ShiftProTypography.caption)
                .foregroundStyle(ShiftProColors.inkSubtle)

            Slider(
                value: Binding(
                    get: { Double(cycleLength) },
                    set: { newValue in
                        cycleLength = Int(newValue)
                        normalizeCycleLength()
                    }
                ),
                in: 2...42,
                step: 1
            )
        }
    }

    private var workDaysSection: some View {
        VStack(alignment: .leading, spacing: ShiftProSpacing.small) {
            Text("Tap Days You Work")
                .font(ShiftProTypography.headline)
                .foregroundStyle(ShiftProColors.ink)

            Text("Tap each day in your cycle that's a work day")
                .font(ShiftProTypography.caption)
                .foregroundStyle(ShiftProColors.inkSubtle)

            workDaysGrid
        }
    }

    private var shiftTimesSection: some View {
        VStack(alignment: .leading, spacing: ShiftProSpacing.small) {
            Text("Shift Times")
                .font(ShiftProTypography.headline)
                .foregroundStyle(ShiftProColors.ink)

            shiftTimePickers
        }
    }

    private var shiftTimePickers: some View {
        HStack(alignment: .center) {
            VStack(alignment: .leading) {
                Text("Start")
                    .font(ShiftProTypography.caption)
                    .foregroundStyle(ShiftProColors.inkSubtle)
                DatePicker("", selection: $startTime, displayedComponents: .hourAndMinute)
                    .labelsHidden()
            }

            Spacer()

            Image(systemName: "arrow.right")
                .foregroundStyle(ShiftProColors.inkSubtle)

            Spacer()

            VStack(alignment: .trailing) {
                Text("End")
                    .font(ShiftProTypography.caption)
                    .foregroundStyle(ShiftProColors.inkSubtle)
                DatePicker("", selection: $endTime, displayedComponents: .hourAndMinute)
                    .labelsHidden()
            }
        }
        .padding(ShiftProSpacing.medium)
        .background(ShiftProColors.surface)
        .clipShape(RoundedRectangle(cornerRadius: 16))
    }

    // MARK: - Shift Label Section

    private var shiftLabelSection: some View {
        VStack(alignment: .leading, spacing: ShiftProSpacing.small) {
            Text("Shift Label")
                .font(ShiftProTypography.headline)
                .foregroundStyle(ShiftProColors.ink)

            Text("Single letter shown on calendar (E=Early, N=Night, etc.)")
                .font(ShiftProTypography.caption)
                .foregroundStyle(ShiftProColors.inkSubtle)

            shiftLabelPicker
        }
    }

    private var shiftLabelPicker: some View {
        HStack(spacing: 12) {
            ForEach(["E", "N", "L", "D", "M", "A"], id: \.self) { code in
                shiftCodeButton(code)
            }

            Spacer()

            // Custom input
            TextField("", text: $selectedShiftCode)
                .textFieldStyle(.plain)
                .font(.system(size: 18, weight: .bold, design: .rounded))
                .foregroundStyle(ShiftProColors.ink)
                .frame(width: 44, height: 44)
                .multilineTextAlignment(.center)
                .background(ShiftProColors.surface)
                .clipShape(RoundedRectangle(cornerRadius: 10))
                .overlay(
                    RoundedRectangle(cornerRadius: 10)
                        .strokeBorder(Color.white.opacity(0.1), lineWidth: 1)
                )
                .onChange(of: selectedShiftCode) { _, new in
                    selectedShiftCode = String(new.prefix(1)).uppercased()
                }
        }
        .padding(ShiftProSpacing.medium)
        .background(ShiftProColors.surface)
        .clipShape(RoundedRectangle(cornerRadius: 16))
    }

    private func shiftCodeButton(_ code: String) -> some View {
        let isSelected = selectedShiftCode == code
        let color = ShiftProColors.shiftCodeColor(for: code)

        return Button {
            withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                selectedShiftCode = code
            }
            HapticManager.fire(.selection, enabled: !reduceMotion)
        } label: {
            Text(code)
                .font(.system(size: 18, weight: .bold, design: .rounded))
                .foregroundStyle(isSelected ? .white : color)
                .frame(width: 44, height: 44)
                .background(
                    RoundedRectangle(cornerRadius: 10, style: .continuous)
                        .fill(isSelected ? color : color.opacity(0.15))
                )
                .overlay(
                    RoundedRectangle(cornerRadius: 10, style: .continuous)
                        .strokeBorder(isSelected ? color : .clear, lineWidth: 2)
                )
                .scaleEffect(isSelected ? 1.05 : 1.0)
        }
        .buttonStyle(PlainButtonStyle())
    }

    private var colorPickerSection: some View {
        VStack(alignment: .leading, spacing: ShiftProSpacing.small) {
            Text("Color")
                .font(ShiftProTypography.headline)
                .foregroundStyle(ShiftProColors.ink)

            Text("Choose a color for this pattern in the calendar")
                .font(ShiftProTypography.caption)
                .foregroundStyle(ShiftProColors.inkSubtle)

            colorSwatchGrid
        }
    }

    private var colorSwatchGrid: some View {
        LazyVGrid(columns: Array(repeating: GridItem(.flexible(), spacing: 12), count: 5), spacing: 12) {
            ForEach(ShiftProColors.patternColors, id: \.self) { colorHex in
                colorSwatch(hex: colorHex)
            }
        }
        .padding(ShiftProSpacing.medium)
        .background(ShiftProColors.surface)
        .clipShape(RoundedRectangle(cornerRadius: 16))
    }

    private func colorSwatch(hex: String) -> some View {
        let isSelected = selectedColorHex == hex
        let color = Color(hex: hex) ?? ShiftProColors.success

        return Button {
            withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                selectedColorHex = hex
            }
            HapticManager.fire(.selection, enabled: !reduceMotion)
        } label: {
            Circle()
                .fill(color)
                .frame(width: 44, height: 44)
                .overlay(
                    Circle()
                        .strokeBorder(Color.white, lineWidth: isSelected ? 3 : 0)
                )
                .overlay(
                    Image(systemName: "checkmark")
                        .font(.system(size: 16, weight: .bold))
                        .foregroundStyle(.white)
                        .opacity(isSelected ? 1 : 0)
                )
                .shadow(color: color.opacity(isSelected ? 0.5 : 0.2), radius: isSelected ? 8 : 4, x: 0, y: isSelected ? 4 : 2)
                .scaleEffect(isSelected ? 1.1 : 1.0)
        }
        .buttonStyle(PlainButtonStyle())
    }

    private var previewSection: some View {
        VStack(alignment: .leading, spacing: ShiftProSpacing.small) {
            Text("Preview")
                .font(ShiftProTypography.headline)
                .foregroundStyle(ShiftProColors.ink)

            patternPreviewCalendar
        }
    }

    private var createButtonSection: some View {
        Button {
            createPattern()
        } label: {
            HStack(spacing: 8) {
                if isApplying {
                    ProgressView()
                        .tint(.white)
                } else {
                    Image(systemName: "checkmark.circle.fill")
                }
                Text(createButtonTitle)
                    .fontWeight(.semibold)
                    .lineLimit(1)
                    .minimumScaleFactor(0.8)
            }
            .frame(maxWidth: .infinity)
            .padding(ShiftProSpacing.medium)
            .background(canCreate ? ShiftProColors.accent : ShiftProColors.accent.opacity(0.5))
            .foregroundStyle(.white)
            .clipShape(RoundedRectangle(cornerRadius: 16))
        }
        .disabled(!canCreate || isApplying)
        .shiftProPressable(scale: 0.98, opacity: 0.96, haptic: nil)
    }

    private var canCreate: Bool {
        !resolvedPatternName.isEmpty && !workDays.isEmpty
    }

    private var createButtonTitle: String {
        guard !workDays.isEmpty else {
            return "Create Pattern"
        }
        let workCount = workDays.count
        let offCount = cycleLength - workCount
        return "\(workCount) on, \(offCount) off"
    }

    private var customLengthLabel: String {
        let weeks = cycleLength / 7
        let days = cycleLength % 7
        if weeks > 0 {
            return "\(cycleLength) days (\(weeks)w \(days)d)"
        }
        return "\(cycleLength) days"
    }

    private var workDaysGrid: some View {
        if cycleLength > 14 {
            let weekCount = Int(ceil(Double(cycleLength) / 7.0))
            return AnyView(
                ScrollView(.horizontal, showsIndicators: false) {
                    LazyHStack(spacing: ShiftProSpacing.small) {
                        ForEach(0..<weekCount, id: \.self) { weekIndex in
                            VStack(spacing: ShiftProSpacing.extraSmall) {
                                Text("Week \(weekIndex + 1)")
                                    .font(ShiftProTypography.caption)
                                    .foregroundStyle(ShiftProColors.inkSubtle)

                                ForEach(daysInWeek(weekIndex: weekIndex), id: \.self) { day in
                                    dayToggleCell(for: day)
                                }
                            }
                            .frame(width: 70)
                        }
                    }
                    .padding(.horizontal, ShiftProSpacing.medium)
                }
            )
        }

        let columns = Array(repeating: GridItem(.flexible(), spacing: ShiftProSpacing.small), count: min(cycleLength, 7))
        return AnyView(
            LazyVGrid(columns: columns, spacing: ShiftProSpacing.small) {
                ForEach(0..<cycleLength, id: \.self) { day in
                    dayToggleCell(for: day)
                }
            }
        )
    }

    private var patternPreviewCalendar: some View {
        let calendar = Calendar.current
        let today = calendar.startOfDay(for: Date())
        let previewDays = cycleLength <= 14 ? 14 : min(cycleLength + 7, 42)

        return VStack(alignment: .leading, spacing: ShiftProSpacing.small) {
            HStack {
                Text("Cycle starts on Day \(currentDayInCycle + 1)")
                    .font(ShiftProTypography.caption)
                    .foregroundStyle(ShiftProColors.inkSubtle)
                Spacer()
                Stepper("", value: $currentDayInCycle, in: 0...(max(0, cycleLength - 1)))
                    .labelsHidden()
            }
            ScrollView(previewDays > 14 ? .horizontal : .vertical, showsIndicators: false) {
                HStack(spacing: 4) {
                    ForEach(0..<previewDays, id: \.self) { offset in
                        let date = calendar.date(byAdding: .day, value: offset, to: today) ?? today
                        let dayInCycle = ((offset - currentDayInCycle) % cycleLength + cycleLength) % cycleLength
                        let isWorkDay = workDays.contains(dayInCycle)
                        let isToday = offset == 0

                        VStack(spacing: 2) {
                            Text(dayAbbreviation(for: date))
                                .font(.system(size: 9))
                                .foregroundStyle(ShiftProColors.inkSubtle)

                            Text("\(calendar.component(.day, from: date))")
                                .font(.system(size: 11, weight: isToday ? .bold : .regular))
                                .foregroundStyle(isWorkDay ? .white : ShiftProColors.ink)
                                .frame(width: 22, height: 22)
                                .background(isWorkDay ? ShiftProColors.accent : ShiftProColors.surface)
                                .clipShape(Circle())
                                .overlay(
                                    Circle()
                                        .stroke(isToday ? ShiftProColors.success : .clear, lineWidth: 2)
                                )
                        }
                    }
                }
                .padding(ShiftProSpacing.small)
                .background(ShiftProColors.surface)
                .clipShape(RoundedRectangle(cornerRadius: 12))
            }

            // Summary text
            let workCount = workDays.count
            let offCount = cycleLength - workCount
            Text("\(workCount) work days, \(offCount) off - repeating every \(cycleLength) days")
                .font(ShiftProTypography.caption)
                .foregroundStyle(ShiftProColors.inkSubtle)
        }
    }

    private func normalizeCycleLength() {
        workDays = workDays.filter { $0 < cycleLength }
        currentDayInCycle = min(currentDayInCycle, max(0, cycleLength - 1))
    }

    private func daysInWeek(weekIndex: Int) -> [Int] {
        let start = weekIndex * 7
        let end = min(start + 7, cycleLength)
        return Array(start..<end)
    }

    private func dayToggleCell(for day: Int) -> some View {
        let isWorkDay = workDays.contains(day)
        return Button {
            let anim: Animation? = reduceMotion ? nil : .spring(response: 0.35, dampingFraction: 0.7)
            withAnimation(anim) {
                if isWorkDay {
                    workDays.remove(day)
                } else {
                    workDays.insert(day)
                }
            }
            HapticManager.fire(.impactMedium, enabled: !reduceMotion)
        } label: {
            VStack(spacing: ShiftProSpacing.extraExtraSmall) {
                Text("Day \(day + 1)")
                    .font(ShiftProTypography.caption)
                Text(isWorkDay ? "Work" : "Off")
                    .font(.system(size: 11, weight: .medium))
                    .foregroundStyle(isWorkDay ? .white.opacity(0.9) : ShiftProColors.inkSubtle)
                Image(systemName: isWorkDay ? "briefcase.fill" : "moon.zzz.fill")
                    .font(.system(size: 22))
            }
            .frame(maxWidth: .infinity)
            .frame(height: 76)
            .background(isWorkDay ? ShiftProColors.accent : ShiftProColors.surface)
            .foregroundStyle(isWorkDay ? .white : ShiftProColors.inkSubtle)
            .clipShape(RoundedRectangle(cornerRadius: 12))
            .overlay(
                RoundedRectangle(cornerRadius: 12)
                    .stroke(isWorkDay ? ShiftProColors.accent : ShiftProColors.divider, lineWidth: 2)
            )
        }
        .shiftProPressable(scale: 0.96, opacity: 0.94, haptic: nil)
        .shiftProHoverLift()
    }

    private func dayAbbreviation(for date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "E"
        return String(formatter.string(from: date).prefix(1))
    }

    private var resolvedPatternName: String {
        let trimmed = patternName.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmed.isEmpty {
            return trimmed
        }
        return autoGeneratedName
    }

    private var autoGeneratedName: String {
        let workCount = workDays.count
        let offCount = cycleLength - workCount
        guard workCount > 0, offCount > 0 else {
            return "Custom (\(cycleLength)-day)"
        }
        if isSingleWorkBlock {
            return "\(workCount) on \(offCount) off"
        }
        return "Custom (\(cycleLength)-day)"
    }

    private var isSingleWorkBlock: Bool {
        guard workDays.count > 0, workDays.count < cycleLength else { return false }
        let isWork = (0..<cycleLength).map { workDays.contains($0) }
        var transitions = 0
        for index in 0..<cycleLength {
            let nextIndex = (index + 1) % cycleLength
            if isWork[index] != isWork[nextIndex] {
                transitions += 1
            }
        }
        return transitions == 2
    }

    private func updateAutoName() {
        guard !isNameCustomized else { return }
        let generated = autoGeneratedName
        guard !generated.isEmpty else { return }
        isSettingAutoName = true
        patternName = generated
        isSettingAutoName = false
    }

    private func createPattern() {
        guard canCreate else { return }
        isApplying = true

        // Calculate start time and duration
        let calendar = Calendar.current
        let startComponents = calendar.dateComponents([.hour, .minute], from: startTime)
        let endComponents = calendar.dateComponents([.hour, .minute], from: endTime)

        let startMinutes = (startComponents.hour ?? 9) * 60 + (startComponents.minute ?? 0)
        var endMinutes = (endComponents.hour ?? 17) * 60 + (endComponents.minute ?? 0)
        if endMinutes <= startMinutes {
            endMinutes += 1440  // Next day
        }
        let durationMinutes = endMinutes - startMinutes

        // Create rotation days
        var rotationDays: [PatternDefinition.RotationDayDefinition] = []
        for day in 0..<cycleLength {
            let isWorkDay = workDays.contains(day)
            rotationDays.append(PatternDefinition.RotationDayDefinition(
                index: day,
                isWorkDay: isWorkDay,
                shiftName: isWorkDay ? "Work" : "Off",
                startMinuteOfDay: isWorkDay ? startMinutes : nil,
                durationMinutes: isWorkDay ? durationMinutes : nil
            ))
        }

        // Create pattern definition
        let definition = PatternDefinition(
            name: resolvedPatternName,
            kind: .rotating,
            startMinuteOfDay: startMinutes,
            durationMinutes: durationMinutes,
            rotationDays: rotationDays,
            notes: "\(workDays.count) on / \(cycleLength - workDays.count) off rotation"
        )

        // Calculate the actual start date based on where user is in cycle
        let today = calendar.startOfDay(for: Date())
        let cycleStartDate = calendar.date(byAdding: .day, value: -currentDayInCycle, to: today) ?? today

        // Build and save pattern
        let profile = profiles.first
        let pattern = engine.buildPattern(from: definition, owner: profile)
        pattern.cycleStartDate = cycleStartDate
        pattern.colorHex = selectedColorHex
        pattern.shortCode = selectedShiftCode
        modelContext.insert(pattern)

        for rotationDay in pattern.rotationDays {
            modelContext.insert(rotationDay)
        }

        // Generate shifts for the next 2 months
        let endDate = calendar.date(byAdding: .month, value: 2, to: today) ?? today
        let shifts = engine.generateShifts(for: pattern, from: today, to: endDate, owner: profile)
        for shift in shifts {
            modelContext.insert(shift)
        }

        do {
            try modelContext.save()
            isApplying = false
            showSuccess = true
            HapticManager.fire(.notificationSuccess, enabled: !reduceMotion)
        } catch {
            isApplying = false
            errorMessage = "Failed to save pattern: \(error.localizedDescription)"
            showError = true
            HapticManager.fire(.notificationError, enabled: !reduceMotion)
        }
    }
}

#Preview {
    SimplePatternBuilderView()
        .modelContainer(for: [ShiftPattern.self, Shift.self, UserProfile.self, RotationDay.self])
}
